MODEL = 'gpt-4o'
TEXT_MENTION_TERMINATION = 'STOP'
DOCKER_WORK_DIR = 'tmp'
DOCKER_TIMEOUT=120
MAX_TURNS=15
OPENAI_API_KEY = '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'